# Generated by Django 3.2 on 2023-07-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_genretitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreTitle',
            new_name='TitleGenre',
        ),
    ]
