# Generated by Django 3.2 on 2023-07-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_genretitle_titlegenre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleGenre',
            new_name='GenreTitle',
        ),
    ]
